version: '3.9'
services:
  whatsapp_go:
    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"
    image: "aldinokemal2104/go-whatsapp-web-multidevice:latest"
    build:
      context: .
      dockerfile: ./docker/golang.Dockerfile
    restart: always
    ports:
      - "3000:3000"
    environment:
      - PORT=3000
      - DEBUG=true
      - WEBHOOK_URL=http://yourwebhook.site/handler
    command: >
      ./app/whatsapp
      --webhook=${WEBHOOK_URL}
